In [45]:
%load_ext autoreload
%autoreload 2
from utils import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [36]:
a = np.reshape((np.random.random_sample(5)), (-1, 1))
a

array([[0.20586039],
       [0.63291012],
       [0.62488511],
       [0.06601514],
       [0.76255406]])

In [37]:
b = np.reshape((np.random.random_sample(5)), (-1, 1))

In [43]:
np.reshape(a[a < 0.5], (-1,1))

array([[0.20586039],
       [0.06601514]])

In [38]:
np.vstack((a,b))

array([[0.20586039],
       [0.63291012],
       [0.62488511],
       [0.06601514],
       [0.76255406],
       [0.74955559],
       [0.66584824],
       [0.21761549],
       [0.37377745],
       [0.63662746]])

In [56]:
dataset = generate_1D_monotone_dataset(8)

In [58]:
for i in range(8):
    print(np.count_nonzero(dataset.y == i+1))

11
13
18
8
12
15
10
13
