In [3]:
import sys
sys.path.insert(0, '/home/laura/Documents/stage2018')
from utils import *

In [5]:
t = np.array([4, 4, 1])
np.argwhere(t == np.amax(t)).flatten()

array([0, 1])

In [4]:
np.random.uniform(-1,0,10)

array([-0.49541498, -0.10049821, -0.01345478, -0.16649135, -0.14207335,
       -0.93681546, -0.8667862 , -0.75769653, -0.07025795, -0.10681655])

In [11]:
def normalize(x, min_v, max_v):
    return ((x - min_v)*1.0) / (max_v - min_v) 

values = []
x = []

for i in range(10):
    x1 = random.uniform(0, 1)
    x2 = random.uniform(0, 1)
    x.append((x1, x2))
    v = 1 + x1 + (1/2) * (x2 * x2 - x1 * x1)
    values.append(v)
        
max_v = max(values)
min_v = min(values)
results = []
    
for i in range(10):
    results.append(normalize(values[i], min_v, max_v))
    
x = [x for _, x in sorted(zip(results, x))]
results = np.reshape(np.array([sorted(results)]), (-1, 1))
    
data = np.hstack((np.array(x), results))

In [12]:
results

array([[0.        ],
       [0.25779614],
       [0.53105131],
       [0.55126411],
       [0.68363613],
       [0.78397458],
       [0.80792435],
       [0.82298545],
       [0.92244498],
       [1.        ]])

In [13]:
data

array([[0.24560044, 0.34929416, 0.        ],
       [0.43130473, 0.42318911, 0.25779614],
       [0.37174707, 0.7558574 , 0.53105131],
       [0.87599291, 0.46447474, 0.55126411],
       [0.89817415, 0.60514565, 0.68363613],
       [0.71598207, 0.74454588, 0.78397458],
       [0.72802047, 0.75880482, 0.80792435],
       [0.86621561, 0.73307553, 0.82298545],
       [0.98978268, 0.79776135, 0.92244498],
       [0.5976494 , 0.94302428, 1.        ]])

In [15]:
x1 = data[0,:2]
x2 = data[4,:2]
print(x1, x2)

[0.24560044 0.34929416] [0.89817415 0.60514565]


In [26]:
np.less_equal(x1, x2).all()

True

In [17]:
np.sum(x1 - x2)

-0.9084251985629941

In [20]:
x0 = np.array([1, 1000])
x3 = np.random.uniform(0,x0,2)
print(x3)

[  0.73413999 676.09648896]


In [ ]:
np.array([random.uniform)

In [18]:
a = [(1, 2)]
a.extend([(4, 5)])
a

[(1, 2), (4, 5)]

In [22]:
M = np.zeros((2, 2))
M[0][1] = 1
M

array([[0., 1.],
       [0., 0.]])

In [29]:
t = np.array([[1, 2], [5, 0], [6, -4]])
print(t)
print(t.min(axis=0))
print(t.max(axis=0))

[[ 1  2]
 [ 5  0]
 [ 6 -4]]
[ 1 -4]
[6 2]


In [31]:
a = np.array([[0,1,7,0,0],[3,0,0,2,19]])
print(a)
np.count_nonzero(a)

[[ 0  1  7  0  0]
 [ 3  0  0  2 19]]


5

In [39]:
a = np.array([1, 2, 3])

In [40]:
b = a.copy()
np.random.shuffle(a)
print(a, b)

[3 2 1] [1 2 3]


In [42]:
r = random.sample(range(0, 10), 2)
r

[0, 4]

In [44]:
y = np.array([[1], [2], [4], [4]])

In [46]:
t = np.array([[10]] * 2)
ind = np.array([0, 3])
y[ind] = t
y

array([[10],
       [ 2],
       [ 4],
       [10]])

In [48]:
np.random.choice(np.array([1, 8, 10, 394]), 2)

array([10,  8])

In [2]:
a = [1, 3, 9]
np.max(a)

9

In [12]:
a = np.array([5, 2, 3, 4])
b = np.array([5, 3, 4, 5])
np.greater_equal(b, a)

array([ True,  True,  True,  True])